export interface Skill {
  name: string;
  level: number;
  interest: number;
  importance: number;
  type: string;
}

const skills: Array<Skill> = [
  {
    name: "JavaScript",
    level: 0.95,
    interest: 0.98,
    importance: 1,
    type: "lang",
  },
  {
    name: "Dart",
    level: 0.7,
    interest: 0.9,
    importance: 0.9,
    type: "lang",
  },
  {
    name: "Rust",
    level: 0.05,
    interest: 0.6,
    importance: 0.4,
    type: "lang",
  },
  {
    name: "TypeScript",
    level: 0.3,
    interest: 0.8,
    importance: 0.6,
    type: "lang",
  },
  {
    name: "Java",
    level: 0.1,
    interest: 0.15,
    importance: 0.3,
    type: "lang",
  },
  {
    name: "SCSS",
    level: 0.75,
    interest: 0.55,
    importance: 0.5,
    type: "lang",
  },
  {
    name: "CSS",
    level: 0.8,
    interest: 0.7,
    importance: 0.6,
    type: "lang",
  },
  {
    name: "HTML",
    level: 0.8,
    interest: 0.4,
    importance: 0.6,
    type: "lang",
  },
  {
    name: "Pug",
    level: 0.8,
    interest: 0.8,
    importance: 0.4,
    type: "lang",
  },
  {
    name: "Bash",
    level: 0.45,
    interest: 0.75,
    importance: 0.8,
    type: "lang",
  },
  {
    name: "XML",
    level: 0.6,
    interest: 0.35,
    importance: 0.5,
    type: "lang",
  },
  {
    name: "CSV",
    level: 0.9,
    interest: 0.3,
    importance: 0.5,
    type: "lang",
  },
  {
    name: "Lisp",
    level: 0.4,
    interest: 0.81,
    importance: 0.1,
    type: "lang",
  },
  {
    name: "GraphQL",
    level: 0.78,
    interest: 0.92,
    importance: 0.7,
    type: "lang",
  },
  {
    name: "Less",
    level: 0.63,
    interest: 0.21,
    importance: 0.1,
    type: "lang",
  },
  {
    name: "Markdown",
    level: 0.9,
    interest: 0.8,
    importance: 0.3,
    type: "lang",
  },
  {
    name: "PlantUML",
    level: 0.7,
    interest: 0.54,
    importance: 0.56,
    type: "lang",
  },
  {
    name: "Node.js",
    level: 0.85,
    interest: 0.97,
    importance: 1,
    type: "runtime",
  },
  {
    name: "Duktape",
    level: 0.25,
    interest: 0.58,
    importance: 0.3,
    type: "runtime",
  },
  {
    name: "Deno",
    level: 0.15,
    interest: 0.95,
    importance: 0.6,
    type: "runtime",
  },
  {
    name: "AngularJS",
    level: 0.9,
    interest: 0.2,
    importance: 0.3,
    type: "framework",
  },
  {
    name: "Angular",
    level: 0.14,
    interest: 0.23,
    importance: 0.3,
    type: "framework",
  },
  {
    name: "Ext JS",
    level: 0.4,
    interest: 0.1,
    importance: 0.3,
    type: "framework",
  },
  {
    name: "Bootstrap",
    level: 0.7,
    interest: 0.3,
    importance: 0.7,
    type: "framework",
  },
  {
    name: "Tailwind",
    level: 0.5,
    interest: 0.8,
    importance: 0.5,
    type: "framework",
  },
  {
    name: "React",
    level: 0.85,
    interest: 0.95,
    importance: 0.95,
    type: "lib",
  },
  {
    name: "Hyperapp",
    level: 0.6,
    interest: 0.4,
    importance: 0.3,
    type: "lib",
  },
  {
    name: "d3",
    level: 0.5,
    interest: 0.9,
    importance: 0.8,
    type: "lib",
  },
  {
    name: "jQuery",
    level: 0.6,
    interest: 0.05,
    importance: 0.4,
    type: "lib",
  },
  {
    name: "Flutter",
    level: 0.75,
    interest: 1,
    importance: 0.6,
    type: "framework",
  },
  {
    name: "Next.js",
    level: 0.8,
    interest: 0.86,
    importance: 0.8,
    type: "framework",
  },
  {
    name: "Express",
    level: 0.8,
    interest: 0.5,
    importance: 0.8,
    type: "framework",
  },
  {
    name: "micro",
    level: 0.6,
    interest: 0.7,
    importance: 0.2,
    type: "framework",
  },
  {
    name: "NPM",
    level: 0.82,
    interest: 0.52,
    importance: 0.9,
    type: "tool",
  },
  {
    name: "Yarn",
    level: 0.76,
    interest: 0.82,
    importance: 0.9,
    type: "tool",
  },
  {
    name: "Grunt",
    level: 0.82,
    interest: 0.23,
    importance: 0.4,
    type: "tool",
  },
  {
    name: "Gulp",
    level: 0.74,
    interest: 0.34,
    importance: 0.4,
    type: "tool",
  },
  {
    name: "Parcel",
    level: 0.8,
    interest: 0.72,
    importance: 0.4,
    type: "tool",
  },
  {
    name: "Webpack",
    level: 0.68,
    interest: 0.66,
    importance: 0.4,
    type: "tool",
  },
  {
    name: "Snowpack",
    level: 0.23,
    interest: 0.53,
    importance: 0.4,
    type: "tool",
  },
  {
    name: "Rome",
    level: 0.1,
    interest: 0.62,
    importance: 0.3,
    type: "tool",
  },
  {
    name: "Pulumi",
    level: 0.54,
    interest: 0.97,
    importance: 0.2,
    type: "tool",
  },
  {
    name: "Terraform",
    level: 0.15,
    interest: 0.72,
    importance: 0.4,
    type: "tool",
  },
  {
    name: "Docker",
    level: 0.7,
    interest: 0.78,
    importance: 0.7,
    type: "tool",
  },
  {
    name: "AWS",
    level: 0.57,
    interest: 0.82,
    importance: 0.8,
    type: "cloud",
  },
  {
    name: "GCP",
    level: 0.22,
    interest: 0.92,
    importance: 0.4,
    type: "cloud",
  },
  {
    name: "Digital Ocean",
    level: 0.12,
    interest: 0.68,
    importance: 0.3,
    type: "cloud",
  },
  {
    name: "Heroku",
    level: 0.46,
    interest: 0.52,
    importance: 0.6,
    type: "cloud",
  },
  {
    name: "Vercel",
    level: 0.85,
    interest: 0.85,
    importance: 0.3,
    type: "cloud",
  },
  {
    name: "Render",
    level: 0.22,
    interest: 0.64,
    importance: 0.3,
    type: "cloud",
  },
  {
    name: "MongoDB",
    level: 0.73,
    interest: 0.77,
    importance: 0.6,
    type: "database",
  },
  {
    name: "FaunaDB",
    level: 0.45,
    interest: 0.83,
    importance: 0.2,
    type: "database",
  },
  {
    name: "PostgreSQL",
    level: 0.32,
    interest: 0.85,
    importance: 0.8,
    type: "database",
  },
  {
    name: "Redis",
    level: 0.12,
    interest: 0.55,
    importance: 0.5,
    type: "database",
  },
  {
    name: "ElasticSearch",
    level: 0.23,
    interest: 0.43,
    importance: 0.3,
    type: "database",
  },
  {
    name: "DynamoDB",
    level: 0.12,
    interest: 0.47,
    importance: 0.3,
    type: "database",
  },
  {
    name: "Puppeteer",
    level: 0.54,
    interest: 0.62,
    importance: 0.4,
    type: "lib",
  },
  {
    name: "Electron",
    level: 0.17,
    interest: 0.65,
    importance: 0.3,
    type: "framework",
  },
  {
    name: "Axios",
    level: 0.54,
    interest: 0.72,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Three.js",
    level: 0.22,
    interest: 0.74,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Material UI",
    level: 0.23,
    interest: 0.67,
    importance: 0.1,
    type: "framework",
  },
  {
    name: "Redux",
    level: 0.3,
    interest: 0.42,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Impress.js",
    level: 0.6,
    interest: 0.53,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Storybook",
    level: 0.65,
    interest: 0.57,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Socket.io",
    level: 0.32,
    interest: 0.63,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Highcharts",
    level: 0.63,
    interest: 0.43,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Lodash",
    level: 0.72,
    interest: 0.33,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "NW.js",
    level: 0.43,
    interest: 0.43,
    importance: 0.1,
    type: "framework",
  },
  {
    name: "Serverless",
    level: 0.12,
    interest: 0.67,
    importance: 0.1,
    type: "framework",
  },
  {
    name: "Svelte",
    level: 0.1,
    interest: 0.35,
    importance: 0.1,
    type: "framework",
  },
  {
    name: "Jest",
    level: 0.75,
    interest: 0.71,
    importance: 0.2,
    type: "framework",
  },
  {
    name: "Leaflet",
    level: 0.43,
    interest: 0.64,
    importance: 0.2,
    type: "lib",
  },
  {
    name: "Request",
    level: 0.5,
    interest: 0.31,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Formik",
    level: 0.34,
    interest: 0.56,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Lerna",
    level: 0.14,
    interest: 0.6,
    importance: 0.1,
    type: "tool",
  },
  {
    name: "PostCSS",
    level: 0.23,
    interest: 0.4,
    importance: 0.1,
    type: "framework",
  },
  {
    name: "RxJS",
    level: 0.12,
    interest: 0.71,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Sequelize",
    level: 0.13,
    interest: 0.41,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Mongoose",
    level: 0.72,
    interest: 0.24,
    importance: 0.1,
    type: "lib",
  },
  {
    name: "Polymer",
    level: 0.6,
    interest: 0.25,
    importance: 0.4,
    type: "framework",
  },
  {
    name: "Mocha",
    level: 0.8,
    interest: 0.74,
    importance: 0.6,
    type: "framework",
  },
  {
    name: "Hasura",
    level: 0.73,
    interest: 0.94,
    importance: 0.6,
    type: "framework",
  },
  {
    name: "Framer Motion",
    level: 0.62,
    interest: 0.85,
    importance: 0.2,
    type: "lib",
  },
  {
    name: "Styled Components",
    level: 0.73,
    interest: 0.45,
    importance: 0.2,
    type: "lib",
  },
  {
    name: "Karma",
    level: 0.61,
    interest: 0.31,
    importance: 0.1,
    type: "framework",
  },
  {
    name: "TestCafe",
    level: 0.7,
    interest: 0.56,
    importance: 0.1,
    type: "framework",
  },
];

export default skills;
export const skillTypes = Array.from(
  skills.reduce((set, skill) => set.add(skill.type), new Set<string>())
);
