import TimelineEvent from "./TimelineEvent";
import chroma from "chroma-js";

export const tagColors = {
  general: chroma('darkorange').alpha(.5),
  education: chroma('#ffc000').alpha(1),
  career: chroma(0x0000dd).alpha(1),
  project: chroma(0x296315).alpha(0.5),
  cool: chroma(0xff1f8f).alpha(0.8),
  hobby: chroma('lime').alpha(0.5),
  deliverable: 0x51eaff,
};

export default [
  {
    id: "life",
    start: new Date("August 19, 1993"),
    end: new Date(),
    name: "Life",
    color: "#ddd",
    depth: 0,
    tags: ["general"],
  },
  {
    id: "school",
    start: new Date("September 1, 1999"),
    end: new Date("May 25, 2010"),
    name: "School",
    color: "#ccc",
    depth: 1,
    tags: ["general", "education"],
  },
  {
    id: "university",
    start: new Date("September 1, 2010"),
    end: new Date("May 25, 2014"),
    name: "University",
    color: "#bbbbbb",
    depth: 1,
    tags: ["general", "education"],
  },
  {
    id: "career",
    start: new Date("February 20, 2014"),
    end: new Date(),
    name: "Career",
    color: "#69E2E099",
    depth: 1,
    tags: ["general", "career"],
  },
  {
    id: "junior",
    start: new Date("February 20, 2014"),
    end: new Date("April 4, 2015"),
    name: "Junior",
    color: "#69C2E299",
    depth: 2,
    tags: ["general", "career"],
  },
  {
    id: "middle",
    start: new Date("April 4, 2015"),
    end: new Date("October 16, 2015"),
    name: "Middle",
    color: "#29C2E299",
    depth: 2,
    tags: ["general", "career"],
  },
  {
    id: "middle-continued",
    start: new Date("October 26, 2015"),
    end: new Date("October 26, 2016"),
    name: "Middle",
    color: "#29C2E299",
    depth: 2,
    tags: ["general", "career"],
  },
  {
    id: "senior",
    start: new Date("October 26, 2016"),
    end: new Date(),
    name: "Senior",
    color: "#2952E299",
    depth: 2,
    tags: ["general", "career"],
  },
  {
    id: "large-crm",
    start: new Date("February 20, 2014"),
    end: new Date("August 1, 2015"),
    name: "Large CRM",
    color: "#29522299",
    depth: 3,
    tags: ["career", "project"],
  },
  {
    id: "spreadsheets-app",
    start: new Date("August 1, 2014"),
    end: new Date("October 1, 2014"),
    name: "Web spreadsheets app",
    color: "#29522299",
    depth: 4,
    tags: ["career", "project"],
  },
  {
    id: "iot-asset-management",
    start: new Date("June 15, 2015"),
    end: new Date("October 10, 2015"),
    name: "IoT Asset Management",
    color: "#29522299",
    depth: 4,
    tags: ["career", "project"],
  },
  {
    id: "iot-platform",
    start: new Date("November 1, 2015"),
    end: new Date("August 31, 2019"),
    name: "IoT Platform",
    color: "#29522299",
    depth: 3,
    tags: ["career", "project"],
  },
  {
    id: "polymer-app",
    start: new Date("November 1, 2015"),
    end: new Date("December 20, 2015"),
    name: "Polymer App",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "email-templates",
    start: new Date("January 5, 2016"),
    end: new Date("January 20, 2016"),
    name: "Email templates system",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "leaflet-maps",
    start: new Date("February 5, 2016"),
    end: new Date("February 15, 2016"),
    name: "Abstract Map Component with Leaflet",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "crud-pages",
    start: new Date("February 20, 2016"),
    end: new Date("March 20, 2016"),
    name: "CRUD for one of the resources",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "api-testing-tool",
    start: new Date("March 25, 2016"),
    end: new Date("April 5, 2016"),
    name: "Postman-like API tool",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "analytics-dashboard",
    start: new Date("April 6, 2016"),
    end: new Date("April 10, 2016"),
    name: "Analytics Dashboard",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "xbac",
    start: new Date("April 15, 2016"),
    end: new Date("April 25, 2016"),
    name: "RBAC/ABAC for application",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "session-timeouts",
    start: new Date("June 6, 2016"),
    end: new Date("June 28, 2016"),
    name: "Active Session timeouts",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "password-complexity",
    start: new Date("July 5, 2016"),
    end: new Date("July 15, 2016"),
    name: "Password Complexity indicator",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "dropping-compass",
    start: new Date("August 10, 2016"),
    end: new Date("September 15, 2016"),
    name: "Migrated from Compass to libsass",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "backend-testing",
    start: new Date("September 20, 2016"),
    end: new Date("October 5, 2016"),
    name: "Microframework for Backend unit testing",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "custom-dashboards",
    start: new Date("October 20, 2016"),
    end: new Date("December 25, 2016"),
    name: "Application Customization Framework",
    color: "#29522299",
    depth: 4,
    tags: ["career", "deliverable"],
  },
  {
    id: "iot-gateway",
    start: new Date("March 20, 2017"),
    end: new Date("September 25, 2017"),
    name: "IoT gateway on AWS Lambda",
    color: "#29522299",
    depth: 4,
    tags: ["career", "project"],
  },
  {
    id: "dart-sdk",
    start: new Date("June 10, 2017"),
    end: new Date("June 20, 2017"),
    name: "Dart SDK for Platform APIs",
    color: "#29522299",
    depth: 6,
    tags: ["career", "deliverable", "cool"],
  },
  {
    id: "iot-dashboard",
    start: new Date("May 15, 2017"),
    end: new Date("August 25, 2017"),
    name: "Administration Dashboard for IoT Devices",
    color: "#29522299",
    depth: 5,
    tags: ["career", "deliverable"],
  },
  {
    id: "lambda-tracing",
    start: new Date("June 23, 2017"),
    end: new Date("August 10, 2017"),
    name: "Distributed tracing for AWS Lambda",
    color: "#29522299",
    depth: 6,
    tags: ["career", "deliverable"],
  },
  {
    id: "frontend-lead",
    start: new Date("August 30, 2017"),
    end: new Date("August 31, 2019"),
    name: "Frontend Lead",
    color: "#29522299",
    depth: 4,
    tags: ["career", "general"],
  },
  {
    id: "drop-bower",
    start: new Date("September 5, 2017"),
    end: new Date("September 15, 2017"),
    name: "Migrated away from Bower/RequireJS",
    color: "#29522299",
    depth: 5,
    tags: ["career", "deliverable"],
  },
  {
    id: "traceability-search",
    start: new Date("February 7, 2016"),
    end: new Date("August 24, 2016"),
    name: "Traceability solution on AWS Lambda",
    color: "#29522299",
    depth: 5,
    tags: ["career", "project"],
  },
  {
    id: "experiences-service",
    start: new Date("August 10, 2018"),
    end: new Date("August 30, 2018"),
    name: "WYSIWYG Experiences Service",
    color: "#29522299",
    depth: 5,
    tags: ["career", "deliverable", "cool"],
  },
  {
    id: "traceability-solution",
    start: new Date("September 4, 2018"),
    end: new Date("April 3, 2020"),
    name: "Traceability Solution",
    color: "#29522299",
    depth: 5,
    tags: ["career", "project"],
  },
  {
    id: "satellite-applications",
    start: new Date("November 20, 2018"),
    end: new Date("December 10, 2018"),
    name: "Satellite Applications",
    color: "#29522299",
    depth: 7,
    tags: ["career", "deliverable"],
  },
  {
    id: "traceability-dashboards",
    start: new Date("November 23, 2018"),
    end: new Date("April 23, 2019"),
    name: "Traceability Dashboards",
    color: "#29522299",
    depth: 6,
    tags: ["career", "deliverable"],
  },
  {
    id: "e2e-testcafe",
    start: new Date("January 23, 2018"),
    end: new Date("May 30, 2018"),
    name: "E2E With TestCafe",
    color: "#29522299",
    depth: 5,
    tags: ["career", "deliverable"],
  },
  {
    id: "docker-optimisation",
    start: new Date("March 19, 2018"),
    end: new Date("March 30, 2018"),
    name: "Docker image optimisation",
    color: "#29522299",
    depth: 6,
    tags: ["career", "deliverable"],
  },
  {
    id: "supply-chain-traceability",
    start: new Date("September 1, 2019"),
    end: new Date("March 21, 2020"),
    name: "Supply Chain Traceability",
    color: "#29522299",
    depth: 3,
    tags: ["career", "project"],
  },
  {
    id: "ar-demo",
    start: new Date("February 27, 2019"),
    end: new Date("March 19, 2019"),
    name: "AR App Demo",
    color: "#29522299",
    depth: 7,
    tags: ["career", "deliverable", "cool"],
  },
  {
    id: "platform-quickstart",
    start: new Date("October 10, 2017"),
    end: new Date("November 20, 2017"),
    name: "Platform Quickstart",
    color: "#29522299",
    depth: 5,
    tags: ["career", "deliverable", "cool"],
  },
  {
    id: "pallet-tracking",
    start: new Date("October 15, 2019"),
    end: new Date("April 2, 2020"),
    name: "Pallet Tracking",
    color: "#29522299",
    depth: 4,
    tags: ["career", "project"],
  },
  {
    id: "lambda-service",
    start: new Date("June 20, 2019"),
    end: new Date("July 10, 2019"),
    name: "Service for serverless scripts",
    color: "#29522299",
    depth: 6,
    tags: ["career", "deliverable", "cool"],
  },
  {
    id: "singularity",
    start: new Date("August 1, 2019"),
    end: new Date("September 20, 2019"),
    name: "Singularity",
    color: "#29522299",
    depth: 6,
    tags: ["career", "project", "cool"],
  },
  {
    id: "mlls",
    start: new Date("September 25, 2019"),
    end: new Date("April 20, 2020"),
    name: "My Long Locking Story",
    color: "#29522299",
    depth: 6,
    tags: ["career", "project", "cool"],
  },
  {
    id: "lisp-interpreter",
    start: new Date("March 5, 2020"),
    end: new Date("March 10, 2020"),
    name: "LISP in Dart",
    color: "#29522299",
    depth: 7,
    tags: ["career", "deliverable", "cool"],
  },
  {
    id: "wutch",
    start: new Date("April 1, 2020"),
    end: new Date(),
    name: "Wutch.net",
    color: "#29522299",
    depth: 3,
    tags: ["career", "project", "cool"],
  },
  {
    id: "electronic-music",
    start: new Date("August 9, 2011"),
    end: new Date("October 18, 2014"),
    name: "Electronic music",
    color: "#29522233",
    depth: 2,
    tags: ["general", "hobby"],
  },
  {
    id: "graphic-design",
    start: new Date("February 9, 2012"),
    end: new Date("January 5, 2014"),
    name: "Graphic Design",
    color: "#29522233",
    depth: 3,
    tags: ["general", "hobby"],
  },
  {
    id: "html-taste",
    start: new Date("February 6, 2007"),
    end: new Date("May 26, 2007"),
    name: "First taste of HTML",
    color: "#29522233",
    depth: 3,
    tags: ["general", "career"],
  },
  {
    id: "photoshop-tutorials",
    start: new Date("May 12, 2004"),
    end: new Date("June 26, 2007"),
    name: "Following Photoshop tutorials",
    color: "#29522233",
    depth: 2,
    tags: ["general", "hobby"],
  },
  {
    id: "flutter-articles",
    start: new Date("September 1, 2019"),
    end: new Date("January 19, 2020"),
    name: "Writing articles on Flutter",
    color: "#29522233",
    depth: 7,
    tags: ["career", "cool"],
  },
  {
    id: "oss-contribution",
    start: new Date("November 20, 2019"),
    end: new Date("December 1, 2019"),
    name: "Contributing to Flame Engine",
    color: "#29522233",
    depth: 8,
    tags: ["career", "cool"],
  },
  {
    id: "flutter-clock",
    start: new Date("January 10, 2020"),
    end: new Date("January 19, 2020"),
    name: "Flutter Clock challenge",
    color: "#29522233",
    depth: 8,
    tags: ["career", "cool"],
  },
  {
    id: "redscript",
    start: new Date("October 1, 2015"),
    end: new Date("October 5, 2015"),
    name: "RedScript",
    color: "#29522233",
    depth: 6,
    tags: ["career", "cool"],
  },
  {
    id: "dtg",
    start: new Date("April 1, 2016"),
    end: new Date("April 10, 2016"),
    name: "DTG",
    color: "#29522233",
    depth: 6,
    tags: ["career", "cool"],
  },
  {
    id: "euler-rust",
    start: new Date("December 1, 2016"),
    end: new Date("December 31, 2016"),
    name: "Project Euler in Rust",
    color: "#29522233",
    depth: 5,
    tags: ["career", "cool"],
  },
  {
    id: "yson",
    start: new Date("September 20, 2015"),
    end: new Date("October 10, 2015"),
    name: "YSON",
    color: "#29522233",
    depth: 5,
    tags: ["career", "cool"],
  },
  {
    id: "thng-query",
    start: new Date("February 5, 2018"),
    end: new Date("February 30, 2018"),
    name: "Thng Query",
    color: "#29522233",
    depth: 6,
    tags: ["career", "cool"],
  },
  {
    id: "tohu",
    start: new Date("April 1, 2018"),
    end: new Date("April 20, 2018"),
    name: "Tohu",
    color: "#29522233",
    depth: 6,
    tags: ["career", "cool"],
  },
].map((e) => {
  e.color = chroma.average(e.tags.map((tag) => tagColors[tag])).css();
  return new TimelineEvent(e);
});

export const tags = Object.keys(tagColors);
